version: '3.9'
services:
  redis:
    restart: unless-stopped
    container_name: django_map-redis
    image: redis:4.0.6
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '${REDIS_PORT}:6379'
  rabbitmq:
    restart: unless-stopped
    container_name: django_map-rabbitmq
    image: rabbitmq:3-management
    ports:
      - '${RABBITMQ_ADMIN_PORT}:15672'
      - '${RABBITMQ_PORT}:5672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
  webserver:
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - rabbitmq
    build:
      context: .
      dockerfile: docker/webserver.Dockerfile
    volumes:
      - type: bind
        source: ./logs
        target: /usr/src/app/logs
    ports:
      - "80:80"