# Generated by Django 2.2.24 on 2022-06-05 03:36

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_hash', models.CharField(max_length=32, unique=True)),
                ('customer_primary_email', models.EmailField(max_length=100, unique=True)),
                ('trail_account', models.BooleanField(default=True)),
                ('integration', models.CharField(blank=True, choices=[('STRIPE', 'Stripe')], max_length=20, null=True)),
                ('integration_key', models.CharField(blank=True, max_length=500, null=True)),
                ('integration_payment_active', models.BooleanField(default=False)),
                ('demo_account', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'cust_customer',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('integration', models.CharField(blank=True, choices=[('STRIPE', 'Stripe')], max_length=20, null=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'cust_subscription',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CustomerUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_datetime', models.DateTimeField()),
                ('unit_type', models.CharField(choices=[('SE', 'Source Entity Spot Usage')], max_length=10)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage', to='customer.Customer')),
            ],
            options={
                'verbose_name': 'Customer Usage',
                'verbose_name_plural': 'Customers Usage',
                'db_table': 'cust_usage',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_date', models.DateTimeField(blank=True, null=True)),
                ('deactive_date', models.DateTimeField(blank=True, null=True)),
                ('payment_active_date', models.DateTimeField(blank=True, null=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customer.Customer')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_subscriptions', to='customer.Subscription')),
            ],
            options={
                'verbose_name': 'Customer Subscription',
                'verbose_name_plural': 'Customer Subscriptions',
                'db_table': 'cust_customer_subscription',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('customer_staff', models.BooleanField(default=False)),
                ('customer_admin', models.BooleanField(default=False)),
                ('internal_customer_admin', models.BooleanField(default=False)),
                ('internal_staff', models.BooleanField(default=False)),
                ('internal_admin', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='customer.Customer')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'cust_user',
                'ordering': ('pk',),
            },
        ),
    ]
